// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package database

import (
	"context"
)

const createLink = `-- name: CreateLink :one
insert into links (
  label, value
) values (
  $1, $2
) 
returning link_id, label, value, date
`

type CreateLinkParams struct {
	Label string
	Value string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.Label, arg.Value)
	var i Link
	err := row.Scan(
		&i.LinkID,
		&i.Label,
		&i.Value,
		&i.Date,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :one
delete from links where link_id = $1
returning link_id
`

func (q *Queries) DeleteLink(ctx context.Context, linkID int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteLink, linkID)
	var link_id int64
	err := row.Scan(&link_id)
	return link_id, err
}

const getLink = `-- name: GetLink :one
select link_id, label, value, date from links
where link_id = $1
limit 1
`

func (q *Queries) GetLink(ctx context.Context, linkID int64) (Link, error) {
	row := q.db.QueryRow(ctx, getLink, linkID)
	var i Link
	err := row.Scan(
		&i.LinkID,
		&i.Label,
		&i.Value,
		&i.Date,
	)
	return i, err
}

const listLinks = `-- name: ListLinks :many
select
  link_id, label, value, date
from
  links
`

func (q *Queries) ListLinks(ctx context.Context) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.LinkID,
			&i.Label,
			&i.Value,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
