name: Linkbox CI

on:
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]
    steps:
      - uses: actions/checkout@v6
      - name: Testing ci
        uses: pnpm/setup@c9883cc79df532ad1a7b81bf9ab944ceb090d65c
        with:
          runtime: node@{{ matrix.node-version }}
          cache: true
      - name: Run test
        run: cd web/ && pnpm test && cd -
